### ISSUE TITLE
Broken repo links reference https://github.com/tableau/bridgectl

### ISSUE THREAD

**Issue by bjiusc** [Tab-SE/BridgeCTL#2]
Links on the UI link to what I presume was the old repo where this tool lived, e.g. https://github.com/tableau/bridgectl/blob/main/LICENSE.txt, https://github.com/tableau/bridgectl/issues, https://github.com/tableau/bridgectl/blob/main/README.md

**Comment by sf-jfluckiger** [comment]
Thank you! This has been resolved and will be pushed out in the next release.
https://github.com/Tab-SE/BridgeCTL/wiki/Release_Notes
