### ISSUE TITLE
New release of Bridge available: 20243.24.1112.0850

### ISSUE THREAD

**Issue by bjiusc** [Tab-SE/BridgeCTL#3]
There's a new release available for Tableau Bridge: https://www.tableau.com/support/releases/bridge/20243.24.1112.0850

This version looks like it needs to be added to the `LATEST_RPM_VERSIONS` list in `bridgectl/src/bridge_rpm_tableau_com.py` to build the Docker image using the latest version using the BridgeCTL UI.

Side question: are there release notes published anywhere for new versions of Tableau Bridge? I wasn't able to find any.

**Comment by josephflu** [comment]
Ok, I just pushed bridgectl version 2.3.58 which includes the new version of bridge. I haven't heard of what the fixes are in this release. I'll let you know if I hear.
